### PR TITLE
Auto-Update branches via custom workflow

### LINKED ISSUE #12: Implement custom workflow to auto-update all branches
See https://github.com/flathub/flatpak-external-data-checker/issues/75#issuecomment-1107915817

@Unrud Do you want to give it a try?

### PR DESCRIPTION
**Pull request by priahoud**
- disable standard F.E.D.C check in flathub.json [1]
- enable updates via custom github workflow [2]

[1] https://github.com/flathub/flatpak-external-data-checker#on-flathub
[2] https://github.com/flathub/flatpak-external-data-checker#custom-workflow

Closes #12

### CODE REVIEW

**Comment by darkdragon-001** [comment]
Waiting for removal of branches flathub/flathub#3824

**Comment by darkdragon-001** [comment]
@priahoud Do you have an idea how we can test if the changes are working?

**Comment by darkdragon-001** [comment]
@priahoud would you like to continue maintaining this package as I am no longer using it myself? Should not be much work as long as F.E.D.C's is working correctly...

**Comment by priahoud** [comment]
> @priahoud Do you have an idea how we can test if the changes are working?

Not really, but  the instructions from [the official F.E.D.C. readme](https://github.com/flathub/flatpak-external-data-checker#custom-workflow) are pretty straightforward, and we know it works for the guys at [the dotnet6 Sdk Extension](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6/commit/9a03c9ef8ec4eb61929a0ee50405ec20a8a5d97d), so I am pretty sure it world work for mono6 too.

> @priahoud would you like to continue maintaining this package as I am no longer using it myself? Should not be much work as long as F.E.D.C's is working correctly...

Not sure if I am the best option to take over maintenance of this Extension as I am basically just a user trying to work with Unity on Linux, but I can give it a shot if there is no one else doing it.

**Comment by darkdragon-001** [comment]
> > @priahoud Do you have an idea how we can test if the changes are working?
> 
> Not really, but the instructions from [the official F.E.D.C. readme](https://github.com/flathub/flatpak-external-data-checker#custom-workflow) are pretty straightforward, and we know it works for the guys at [the dotnet6 Sdk Extension](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6/commit/9a03c9ef8ec4eb61929a0ee50405ec20a8a5d97d), so I am pretty sure it world work for mono6 too.

There could be a typo or similar which is difficult to spot just by inspection for review. Nevertheless, I think it is the right approach. We should just both check if there is a PR when the next update is released, just to make sure!

> > @priahoud would you like to continue maintaining this package as I am no longer using it myself? Should not be much work as long as F.E.D.C's is working correctly...
> 
> Not sure if I am the best option to take over maintenance of this Extension as I am basically just a user trying to work with Unity on Linux, but I can give it a shot if there is no one else doing it.

I was basically just copying the stuff from mono5 and doing similar PRs as you did so far. If you need help, you can either tag me or any of the Flathub maintainers or ask in the chat. Usually people are very open and often even proactive to help out. Might not be instant though as most people work on it in their free time. I requested access for you https://github.com/flathub/flathub/issues/3825.

**Comment by priahoud** [comment]
> There could be a typo or similar which is difficult to spot just by inspection for review. Nevertheless, I think it is the right approach. We should just both check if there is a PR when the next update is released, just to make sure!

Allright. I will keep an eye on it.

> I was basically just copying the stuff from mono5 and doing similar PRs as you did so far. If you need help, you can either tag me or any of the Flathub maintainers or ask in the chat. Usually people are very open and often even proactive to help out. Might not be instant though as most people work on it in their free time.

Got it, thank you!

> I requested access for you [flathub/flathub#3825](https://github.com/flathub/flathub/issues/3825).

Thanks again!

**Pull request merged**
